version: "3.7"

networks:
  server-connection:
    driver: bridge

services:
  nginx:
    container_name: nginx-proxy-hoppang
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/api-hoppang.shop/fullchain.pem:/etc/nginx/ssl/certificate.crt:ro
      - /etc/letsencrypt/live/api-hoppang.shop/privkey.pem:/etc/nginx/ssl/private.key:ro
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - back-end-app
      - web-front-end-app
      - admin-front-end-app

  database:
    container_name: hoppang_database
    image: mysql:8.0.33
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: hoppang
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234567
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 20s
      retries: 10
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - server-connection

  back-end-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hoppang_main_back
    restart: on-failure
    expose:
      - "9090"
    depends_on:
      - database
    command:
      - ./gradlew bootRun
      - chmod 777 /be-app/logs
      - chown root:root /be-app/logs
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TZ=Asia/Seoul
    networks:
      - server-connection
    volumes:
      - /home/twj/hoppang-app/logs:/be-app/logs
    user: root

  admin-front-end-app:
    container_name: hoppang_admin_front
    image: dndxowjd/hoppang-admin-fe:0.01
    restart: always
    expose:
      - "10234"
    networks:
      - server-connection

  web-front-end-app:
    container_name: hoppang_web_front
    image: dndxowjd/hoppang-web-fe:0.01
    restart: always
    expose:
      - "10244"
    networks:
      - server-connection

volumes:
  dev-log:
    external: true