version: "3.7"

services:
  database:
    image: mysql:8.0.33
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: hoppang
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234567
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 20s
      retries: 10
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
