version: "3.7"

networks:
  server-connection:
    driver: bridge

services:
  reverse-nginx:
    container_name: nginx-proxy-hoppang
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/hoppang.store/fullchain.pem:/etc/nginx/ssl/hoppang-store-certificate.crt:ro # hoppang.store 인증서
      - /etc/letsencrypt/live/hoppang.store/privkey.pem:/etc/nginx/ssl/hoppang-store-private.key:ro # hoppang.store 인증서
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - back-end-app
      - web-front-end-app
      - admin-front-end-app

  database-master:
    container_name: hoppang_database_master
    build:
      context: ./
      dockerfile: master/Dockerfile
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: hoppang
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 1234567
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - my-db-master:/var/lib/mysql
      - my-db-master:/var/lib/mysql-files
    networks:
      - server-connection

  database-slave:
    container_name: hoppang_database_slave
    build:
      context: ./
      dockerfile: slave/Dockerfile
    restart: unless-stopped
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: hoppang
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 1234567
      TZ: 'Asia/Seoul'
    ports:
      - "3308:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - my-db-slave:/var/lib/mysql
      - my-db-slave:/var/lib/mysql-files
    networks:
      - server-connection
    depends_on:
      - database-master

  back-end-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hoppang_main_back
    restart: on-failure
    expose:
      - "9090"
    depends_on:
      - database-master
      - database-slave
    command:
      - ./gradlew bootRun
      - chmod 777 /be-app/logs
      - chown root:root /be-app/logs
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - HOPPANG_SLACK_BOT_TOKEN=${HOPPANG_SLACK_BOT_TOKEN}
      - TZ=Asia/Seoul
    networks:
      - server-connection
    volumes:
      - /home/twj/hoppang-app/logs:/be-app/logs
    user: root

  admin-front-end-app:
    container_name: hoppang_admin_front
    image: dndxowjd/hoppang-admin-fe:0.01
    restart: always
    expose:
      - "10234"
    networks:
      - server-connection

  web-front-end-app:
    container_name: hoppang_web_front
    image: dndxowjd/hoppang-web-fe:0.01
    restart: always
    expose:
      - "10244"
    networks:
      - server-connection

volumes:
  dev-log:
    external: true
  my-db-master:
  my-db-slave: