version: "3.7"

networks:
  server-connection:
    driver: bridge

services:
  nginx:
    container_name: nginx_tws_back_hoppang
    image: nginx
    restart: always
    ports:
      - '25640:25640'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - app

  database:
    container_name: hoppang_database
    image: mysql:8.0.33
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: hoppang
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234567
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3307"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 20s
      retries: 10
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - server-connection

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: twj_spring_hoppang
    restart: on-failure
    expose:
      - "9090"
    depends_on:
      - database
    command:
      - ./gradlew bootRun
      - chmod 777 /app/logs
      - chown root:root /app/logs
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TZ=Asia/Seoul
    networks:
      - server-connection
    volumes:
      - /home/twj/hoppang-app/logs:/app/logs
    user: root

volumes:
  dev-log:
    external: true