global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'back-end-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [
        'back-end-app:9090',
        'back-end-app:9091',
        'back-end-app:9093'
      ]