global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:8080"
  - job_name: 'back-end-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']