global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'back-end-app'
    scrape_interval: 5s
    static_configs:
      - metric_path: '/actuator/prometheus'
      - targets: ['back-end-app:9090']