global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

scrape_configs:
  - job_name: 'back-end-app'
    metrics_path: '/hoppang/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['back-end-app']