server:
  port: 7070
  front:
    admin-page-origin-url: ${FRONT_ORIGIN_URL}
    web-page-origin-url: ${FRONT_ORIGIN_URL}

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 5
        event:
          merge:
            entity_copy_observer: allow
    database: mysql
    open-in-view: false
  datasource:
    master:
      jdbcUrl: jdbc:mysql://localhost:3307/hoppang?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234567
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://localhost:3307/hoppang?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234567
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 1
          min-idle: 0
          time-between-eviction-runs: 20

  flyway:
    user: root
    password: 1234567
    url: jdbc:mysql://localhost:3307/hoppang?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      base-path: /hoppang
      exposure:
        include: prometheus, health, info
    enabled-by-default: false
  endpoint:
      health:
        enabled: true
      prometheus:
        enabled: true
      info:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  secret-key: ${JWT_SECRET_KEY}

slack:
  token: ${HOPPANG_SLACK_BOT_TOKEN}
  channel:
    monitor:
      error: '#에러-dev'
      new-estimation: '#샤시견적-dev'
      new-user: '#유저-인입-dev'

login:
  kakao:
    rest-api-key: da09bfccea21381b988c8ede053a85c5
    redirect-uri: http://localhost:3000/chassis/calculator

---

server:
  port: 9090
  front:
    admin-page-origin-url: http://api-hoppang.shop
    web-page-origin-url: https://hoppang.store

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 5
        event:
          merge:
            entity_copy_observer: allow
    database: mysql
    open-in-view: false
  datasource:
    master:
      jdbcUrl: jdbc:mysql://database-master:3306/hoppang?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234567
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://database-slave:3306/hoppang?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234567
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    redis:
      host: cache-redis
      port: 6379
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 1
          min-idle: 0
          time-between-eviction-runs: 20

  flyway:
    user: root
    password: 1234567
    url: jdbc:mysql://database-master:3306/hoppang?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: /app/logs/server.log
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%highlight(%logger.%method:%line)] - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger{36}] - %msg%n"
    level: DEBUG
  logback:
    rollingpolicy:
      file-name-pattern: "/app/logs/server.%d{yyyy-MM-dd}.%i.log.gz" # 로그 파일을 gzip으로 압축
      max-history: 30  # 30일 동안 로그 보관

management:
  endpoints:
    web:
      base-path: /hoppang
      exposure:
        include: prometheus, health, info
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  secret-key: ${JWT_SECRET_KEY}

slack:
  token: ${HOPPANG_SLACK_BOT_TOKEN}
  channel:
    monitor:
      error: '#에러'
      new-estimation: '#샤시견적'
      new-user: '#유저-인입'

login:
  kakao:
    rest-api-key: da09bfccea21381b988c8ede053a85c5
    redirect-uri: https://hoppang.store/chassis/calculator
