server:
  port: 7070
  front:
    origin-url: ${FRONT_ORIGIN_URL}

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 5
        event:
          merge:
            entity_copy_observer: allow
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3307/hoppang?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    user: root
    password: 1234567
    url: jdbc:mysql://localhost:3307/hoppang?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET_KEY}

---

server:
  port: 9090
  front:
    origin-url: https://59.6.25.248

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 5
        event:
          merge:
            entity_copy_observer: allow
    database: mysql
  datasource:
    url: jdbc:mysql://database:3306/hoppang?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    user: root
    password: 1234567
    url: jdbc:mysql://database:3306/hoppang?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET_KEY}